/**
 * /meta scorecard — the portal grades itself in public.
 *
 * Three sources:
 *  - build-time, imported statically from src/data/portal-stats.json
 *    (test count, deployed commit, build date) — generated by
 *    scripts/build-portal-stats.mjs at prebuild;
 *  - Lighthouse, imported statically from src/data/lighthouse-history.json
 *    — appended after every successful deploy by the lighthouse workflow,
 *    which measures the live production site, so the file's git history is
 *    the score timeline and the tile shows the latest run;
 *  - live, fetched on mount from /api/health (service health) and
 *    /api/meta/stats (intake-response median vs the 72h SLA, shipped count).
 *
 * Everything degrades gracefully: if a fetch fails (e.g. `vite dev` without
 * the Functions runtime) or Lighthouse hasn't run yet, the tile reads "—"
 * instead of breaking.
 */

import { useEffect, useState } from 'react'
import type { Lang } from '../i18n'
import { formatDate } from '../lib/format'
import stats from '../data/portal-stats.json'
import lighthouse from '../data/lighthouse-history.json'

interface BuildStats {
  testCount: number
  commit: string
  builtAt: string
}

interface LighthouseRun {
  commit: string
  date: string
  performance: number | null
  accessibility: number | null
  bestPractices: number | null
  seo: number | null
}

interface LiveStats {
  shippedCount: number
  medianResponseHours: number | null
  sampleSize: number
  slaHours: number
}

type Health = 'loading' | 'ok' | 'down'

const COPY = {
  fr: {
    eyebrow: 'a2 · le bulletin du portail',
    title: 'Le portail, noté en public',
    lead: "Pas de captures d'écran de tableaux de bord. Les chiffres ci-dessous sont mesurés : certains figés au moment du déploiement, d'autres lus en direct à l'ouverture de cette page.",
    tests: 'Tests automatisés',
    testsSub: 'exécutés à chaque build',
    perf: 'Performance',
    perfSub: (iso: string) => `Lighthouse · ${formatDate(iso, 'fr')}`,
    perfPending: 'première mesure à venir',
    health: 'Service',
    healthOk: 'opérationnel',
    healthDown: 'dégradé',
    healthLoading: 'vérification…',
    healthSub: 'vérifié à la seconde',
    response: 'Réponse à l’intake',
    responseSub: (sla: number) => `médiane · cible ${sla} h`,
    responsePending: 'premier dossier à venir',
    shipped: 'Projets livrés',
    shippedSub: 'engagements menés à terme',
    build: 'Build déployé',
    buildSub: (iso: string) => `déployé le ${formatDate(iso, 'fr')}`,
    unavailable: 'indisponible',
  },
  en: {
    eyebrow: 'a2 · the portal report card',
    title: 'The portal, graded in public',
    lead: 'No dashboard screenshots. The numbers below are measured — some frozen at deploy time, some read live when this page opens.',
    tests: 'Automated tests',
    testsSub: 'run on every build',
    perf: 'Performance',
    perfSub: (iso: string) => `Lighthouse · ${formatDate(iso, 'en')}`,
    perfPending: 'first measurement pending',
    health: 'Service',
    healthOk: 'operational',
    healthDown: 'degraded',
    healthLoading: 'checking…',
    healthSub: 'checked just now',
    response: 'Intake response',
    responseSub: (sla: number) => `median · ${sla}h target`,
    responsePending: 'first case still to come',
    shipped: 'Projects shipped',
    shippedSub: 'engagements carried to completion',
    build: 'Deployed build',
    buildSub: (iso: string) => `deployed ${formatDate(iso, 'en')}`,
    unavailable: 'unavailable',
  },
} as const

export function Scorecard({ lang }: { lang: Lang }) {
  const t = COPY[lang]
  const build = stats as BuildStats

  // Latest Lighthouse run — the history file grows append-only in CI, so the
  // last entry is the most recent measurement. Empty until CI first runs.
  const runs = (lighthouse as { runs: LighthouseRun[] }).runs
  const lastRun = runs.length > 0 ? runs[runs.length - 1] : null

  const [health, setHealth] = useState<Health>('loading')
  const [live, setLive] = useState<LiveStats | null>(null)
  const [liveFailed, setLiveFailed] = useState(false)

  useEffect(() => {
    let cancelled = false

    fetch('/api/health')
      .then((r) => r.json() as Promise<{ ok?: boolean }>)
      .then((d) => {
        if (!cancelled) setHealth(d?.ok ? 'ok' : 'down')
      })
      .catch(() => {
        if (!cancelled) setHealth('down')
      })

    fetch('/api/meta/stats')
      .then((r) => {
        if (!r.ok) throw new Error(`stats ${r.status}`)
        return r.json() as Promise<LiveStats>
      })
      .then((d) => {
        if (!cancelled) setLive(d)
      })
      .catch(() => {
        if (!cancelled) setLiveFailed(true)
      })

    return () => {
      cancelled = true
    }
  }, [])

  // Intake-response tile: green when the median beats the SLA, amber when
  // it slips past it, neutral while there is no case to measure yet.
  const responseValue =
    live && live.medianResponseHours !== null ? `${live.medianResponseHours} h` : '—'
  const responseState =
    live && live.medianResponseHours !== null
      ? live.medianResponseHours <= live.slaHours
        ? 'ok'
        : 'warn'
      : 'idle'
  const responseSub =
    live && live.medianResponseHours !== null
      ? t.responseSub(live.slaHours)
      : liveFailed
        ? t.unavailable
        : t.responsePending

  const healthState = health === 'ok' ? 'ok' : health === 'down' ? 'warn' : 'idle'
  const healthValue =
    health === 'ok' ? t.healthOk : health === 'down' ? t.healthDown : t.healthLoading

  const shippedValue = live ? String(live.shippedCount) : liveFailed ? '—' : '…'

  // Performance tile: Lighthouse's own green threshold is 90.
  const perf = lastRun?.performance ?? null
  const perfValue = perf !== null ? String(perf) : '—'
  const perfState = perf === null ? 'idle' : perf >= 90 ? 'ok' : 'warn'
  const perfSub = lastRun ? t.perfSub(lastRun.date) : t.perfPending

  return (
    <section className="scorecard" aria-label={t.title}>
      <div className="scorecard__head">
        <div className="section__eyebrow">{t.eyebrow}</div>
        <h2 className="scorecard__title">{t.title}</h2>
        <p className="scorecard__lead">{t.lead}</p>
      </div>
      <ul className="scorecard__grid">
        <li className="surface scorecard__tile">
          <span className="scorecard__value">{build.testCount}</span>
          <span className="scorecard__label">{t.tests}</span>
          <span className="scorecard__sub mono">{t.testsSub}</span>
        </li>
        <li className={`surface scorecard__tile scorecard__tile--${perfState}`}>
          <span className="scorecard__value">{perfValue}</span>
          <span className="scorecard__label">{t.perf}</span>
          <span className="scorecard__sub mono">{perfSub}</span>
        </li>
        <li className={`surface scorecard__tile scorecard__tile--${healthState}`}>
          <span className="scorecard__value scorecard__value--word">{healthValue}</span>
          <span className="scorecard__label">{t.health}</span>
          <span className="scorecard__sub mono">{t.healthSub}</span>
        </li>
        <li className={`surface scorecard__tile scorecard__tile--${responseState}`}>
          <span className="scorecard__value">{responseValue}</span>
          <span className="scorecard__label">{t.response}</span>
          <span className="scorecard__sub mono">{responseSub}</span>
        </li>
        <li className="surface scorecard__tile">
          <span className="scorecard__value">{shippedValue}</span>
          <span className="scorecard__label">{t.shipped}</span>
          <span className="scorecard__sub mono">{t.shippedSub}</span>
        </li>
        <li className="surface scorecard__tile">
          <span className="scorecard__value scorecard__value--word mono">{build.commit}</span>
          <span className="scorecard__label">{t.build}</span>
          <span className="scorecard__sub mono">{t.buildSub(build.builtAt)}</span>
        </li>
      </ul>
    </section>
  )
}
